//Estamos ante una aplicación que consiste principalmente en recordar una serie de imágenes para luego ponerlas abajo.
//Esta serie de imágenes, tendrán que ser recordadas. Al final del juego, pulsaremos un botón de contar aciertos.
//Si hemos contestado a todas bien, se podrá pasar de nivel.
//La aplicación consta de:
/** 
 * -16 Botones inferiores que sirven para indicar las imágenes.
 * -7 jLabels. 4 iniciales para las imágenes a recordar y hasta 7 mientras vaya subiendo el nivel.
 * -3 Botones que indicarán el comienzo, el recordar las imágenes y el contar los aciertos.
 * -1 jLabel que dirá el número de aciertos que tienes.
 */
package exament3;
//Lo primero que hacemos es importar todo lo que necesitemos usar.
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VentanaIconos extends javax.swing.JFrame {
//Creamos unas variables en el public class para que podamos utilizarlas durante todo el proceso de programación.
    //el número de imágenes a acertar va a indicar los aciertos iniciales que tenemos que tener para pasar de nivel.
    
    String secuenciaJuego = "";
    String secuenciaBotonesMostrados = "";
    String secuenciaPulsada = "";
    int numImagenesAcertar = 4;

    public VentanaIconos() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMuestra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelBotonIcono = new javax.swing.JPanel();
        jToggleButtonI9 = new javax.swing.JToggleButton();
        jToggleButtonI1 = new javax.swing.JToggleButton();
        jToggleButtonI13 = new javax.swing.JToggleButton();
        jToggleButtonI3 = new javax.swing.JToggleButton();
        jToggleButtonI4 = new javax.swing.JToggleButton();
        jToggleButtonI14 = new javax.swing.JToggleButton();
        jToggleButtonI11 = new javax.swing.JToggleButton();
        jToggleButtonI10 = new javax.swing.JToggleButton();
        jToggleButtonI16 = new javax.swing.JToggleButton();
        jToggleButtonI12 = new javax.swing.JToggleButton();
        jToggleButtonI5 = new javax.swing.JToggleButton();
        jToggleButtonI2 = new javax.swing.JToggleButton();
        jToggleButtonI15 = new javax.swing.JToggleButton();
        jToggleButtonI7 = new javax.swing.JToggleButton();
        jToggleButtonI6 = new javax.swing.JToggleButton();
        jToggleButtonI8 = new javax.swing.JToggleButton();
        jPanelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelAciertos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanelMuestra.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMuestraLayout = new javax.swing.GroupLayout(jPanelMuestra);
        jPanelMuestra.setLayout(jPanelMuestraLayout);
        jPanelMuestraLayout.setHorizontalGroup(
            jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMuestraLayout.setVerticalGroup(
            jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelBotonIcono.setBackground(new java.awt.Color(204, 255, 255));
        jPanelBotonIcono.setOpaque(false);

        jToggleButtonI9.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI9.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI9ActionPerformed(evt);
            }
        });

        jToggleButtonI1.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI1.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI1ActionPerformed(evt);
            }
        });

        jToggleButtonI13.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI13.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI13ActionPerformed(evt);
            }
        });

        jToggleButtonI3.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI3.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI3ActionPerformed(evt);
            }
        });

        jToggleButtonI4.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI4.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI4ActionPerformed(evt);
            }
        });

        jToggleButtonI14.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI14.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI14ActionPerformed(evt);
            }
        });

        jToggleButtonI11.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI11.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI11ActionPerformed(evt);
            }
        });

        jToggleButtonI10.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI10.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI10ActionPerformed(evt);
            }
        });

        jToggleButtonI16.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI16.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI16ActionPerformed(evt);
            }
        });

        jToggleButtonI12.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI12.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI12ActionPerformed(evt);
            }
        });

        jToggleButtonI5.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI5.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI5ActionPerformed(evt);
            }
        });

        jToggleButtonI2.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI2.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jToggleButtonI15.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI15.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI15ActionPerformed(evt);
            }
        });

        jToggleButtonI7.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI7.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI7ActionPerformed(evt);
            }
        });

        jToggleButtonI6.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI6.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI6ActionPerformed(evt);
            }
        });

        jToggleButtonI8.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButtonI8.setForeground(new java.awt.Color(204, 255, 255));
        jToggleButtonI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonIconoLayout = new javax.swing.GroupLayout(jPanelBotonIcono);
        jPanelBotonIcono.setLayout(jPanelBotonIconoLayout);
        jPanelBotonIconoLayout.setHorizontalGroup(
            jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                                .addComponent(jToggleButtonI1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonI2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                                .addComponent(jToggleButtonI5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonI7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonI3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonI4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addComponent(jToggleButtonI9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addComponent(jToggleButtonI13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanelBotonIconoLayout.setVerticalGroup(
            jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonI1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonI5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jToggleButtonI6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jToggleButtonI8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButtonI9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonI11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButtonI12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToggleButtonI10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonI13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanelBotones.setBackground(new java.awt.Color(204, 255, 255));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Recordar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Empezar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Comprobar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelAciertos.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelAciertos.setForeground(new java.awt.Color(0, 0, 255));
        jLabelAciertos.setText("  ");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelAciertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabelAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Memory game");

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Copyright by : Ramón Guardia López");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBotonIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBotonIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI4ActionPerformed
    }//GEN-LAST:event_jToggleButtonI4ActionPerformed

    private void jToggleButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI1ActionPerformed
    }//GEN-LAST:event_jToggleButtonI1ActionPerformed

    private void jToggleButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI3ActionPerformed
    }//GEN-LAST:event_jToggleButtonI3ActionPerformed

    private void jToggleButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI5ActionPerformed
    }//GEN-LAST:event_jToggleButtonI5ActionPerformed

    private void jToggleButtonI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI6ActionPerformed
    }//GEN-LAST:event_jToggleButtonI6ActionPerformed

    private void jToggleButtonI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI7ActionPerformed
    }//GEN-LAST:event_jToggleButtonI7ActionPerformed

    private void jToggleButtonI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI8ActionPerformed
    }//GEN-LAST:event_jToggleButtonI8ActionPerformed

    private void jToggleButtonI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI9ActionPerformed
    }//GEN-LAST:event_jToggleButtonI9ActionPerformed

    private void jToggleButtonI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI10ActionPerformed
    }//GEN-LAST:event_jToggleButtonI10ActionPerformed

    private void jToggleButtonI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI11ActionPerformed
    }//GEN-LAST:event_jToggleButtonI11ActionPerformed

    private void jToggleButtonI12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI12ActionPerformed
    }//GEN-LAST:event_jToggleButtonI12ActionPerformed

    private void jToggleButtonI13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI13ActionPerformed
    }//GEN-LAST:event_jToggleButtonI13ActionPerformed

    private void jToggleButtonI14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI14ActionPerformed
    }//GEN-LAST:event_jToggleButtonI14ActionPerformed

    private void jToggleButtonI15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI15ActionPerformed
    }//GEN-LAST:event_jToggleButtonI15ActionPerformed

    private void jToggleButtonI16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI16ActionPerformed
    }//GEN-LAST:event_jToggleButtonI16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //En el botón segundo, vamos a hacer un Random que genere 16 números aleatorios (0 a 16)
        Random generadorNum = new Random();
        secuenciaBotonesMostrados = "";
        //Luego hacemos un for en el que vamos a tener un contador que mientras sea menor que 16 (el número de posiciones genradas por el Random), se aumente.
		for (int i = 0; i < 16; i++) {
                    //Creamos un char que contenga el la sucesión de números que pasaremos a letras.
            char letra = (char) (generadorNum.nextInt(16) + 'A');
            //Añadimos al String la cadena de letras.
            secuenciaBotonesMostrados += letra;
        }
 	
        

        secuenciaPulsada = "";
        //Al pulsar el botón,  se activan los botones para que podamos empezar a jugar.
        jToggleButtonI1.setEnabled(true);
        jToggleButtonI2.setEnabled(true);
        jToggleButtonI3.setEnabled(true);
        jToggleButtonI4.setEnabled(true);
        jToggleButtonI5.setEnabled(true);
        jToggleButtonI6.setEnabled(true);
        jToggleButtonI7.setEnabled(true);
        jToggleButtonI8.setEnabled(true);
        jToggleButtonI9.setEnabled(true);
        jToggleButtonI10.setEnabled(true);
        jToggleButtonI11.setEnabled(true);
        jToggleButtonI12.setEnabled(true);
        jToggleButtonI13.setEnabled(true);
        jToggleButtonI14.setEnabled(true);
        jToggleButtonI15.setEnabled(true);
        jToggleButtonI16.setEnabled(true);

        try {
            /**
             * Dentro del try, tenemos los iconos que queremos que se muestren. Para ello, cogemos de la cadena
             * que hicimos antes el valor correspondiente dependiendo de la posición del botón. Es decir,
             * para el botón 1, cogemos el carácter 1.
             */
            jToggleButtonI1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(0) + ".png"))));
            jToggleButtonI2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(1) + ".png"))));
            jToggleButtonI3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(2) + ".png"))));
            jToggleButtonI4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(3) + ".png"))));
            jToggleButtonI5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(4) + ".png"))));
            jToggleButtonI6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(5) + ".png"))));
            jToggleButtonI7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(6) + ".png"))));
            jToggleButtonI8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(7) + ".png"))));
            jToggleButtonI9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(8) + ".png"))));
            jToggleButtonI10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(9) + ".png"))));
            jToggleButtonI11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(10) + ".png"))));
            jToggleButtonI12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(11) + ".png"))));
            jToggleButtonI13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(12) + ".png"))));
            jToggleButtonI14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(13) + ".png"))));
            jToggleButtonI15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(14) + ".png"))));
            jToggleButtonI16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaBotonesMostrados.charAt(15) + ".png"))));
            //Mientras haya imágenes en los botones del juego, las imágenes a recordar desaparecerán.
            jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jLabel7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Se ha producido un error inesperado\n" + e.getMessage());
            System.exit(0);
        }
        
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /**
         * El siguiente Random, tiene prácticamente la misma función que el anterior.
         * La diferencia viene cuando hacemos el for, que en este caso mientras el incremento sea
         * menor que el número de imágenes que tenemos que acertar, su valor aumentará.
         */
        Random generadorNum = new Random();
        secuenciaJuego = "";
        for (int i = 0; i < numImagenesAcertar; i++) {
            
                char letra = (char) (generadorNum.nextInt(16) + 'A');
            secuenciaJuego += letra;
            
       }

        jToggleButtonI1.setEnabled(false);
        jToggleButtonI2.setEnabled(false);
        jToggleButtonI3.setEnabled(false);
        jToggleButtonI4.setEnabled(false);
        jToggleButtonI5.setEnabled(false);
        jToggleButtonI6.setEnabled(false);
        jToggleButtonI7.setEnabled(false);
        jToggleButtonI8.setEnabled(false);
        jToggleButtonI9.setEnabled(false);
        jToggleButtonI10.setEnabled(false);
        jToggleButtonI11.setEnabled(false);
        jToggleButtonI12.setEnabled(false);
        jToggleButtonI13.setEnabled(false);
        jToggleButtonI14.setEnabled(false);
        jToggleButtonI15.setEnabled(false);
        jToggleButtonI16.setEnabled(false);

        jToggleButtonI1.setSelected(false);
        jToggleButtonI2.setSelected(false);
        jToggleButtonI3.setSelected(false);
        jToggleButtonI4.setSelected(false);
        jToggleButtonI5.setSelected(false);
        jToggleButtonI6.setSelected(false);
        jToggleButtonI7.setSelected(false);
        jToggleButtonI8.setSelected(false);
        jToggleButtonI9.setSelected(false);
        jToggleButtonI10.setSelected(false);
        jToggleButtonI11.setSelected(false);
        jToggleButtonI12.setSelected(false);
        jToggleButtonI13.setSelected(false);
        jToggleButtonI14.setSelected(false);
        jToggleButtonI15.setSelected(false);
        jToggleButtonI16.setSelected(false);

        try {
            switch (numImagenesAcertar) {
                case 7:
                    jLabel7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(6) + ".png"))));
                case 6:
                    jLabel6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(5) + ".png"))));
                case 5:
                    jLabel5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(4) + ".png"))));
                case 4:
                    jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(0) + ".png"))));
                    jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(1) + ".png"))));
                    jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(2) + ".png"))));
                    jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + secuenciaJuego.charAt(3) + ".png"))));
                    break;
            
            }

            jToggleButtonI1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
            jToggleButtonI16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Se ha producido un error inesperado\n" + e.getMessage());
            System.exit(0);
        }
        
            
            
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /**
         * El botón de contar aciertos tiene la función de buscar la letra que haya en cada posición.
         * Si el botón está selecionado y el contenido del mismo es igual al que tenemos  arriba, entonces 
         * incrementaremos el contador de aciertos.
         */
        int contadorAciertos = 0;

        if (jToggleButtonI1.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(0)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI1.setEnabled(false);
        }

        if (jToggleButtonI2.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(1)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI2.setEnabled(false);
        }

        if (jToggleButtonI3.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(2)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI3.setEnabled(false);
        }

        if (jToggleButtonI4.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(3)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI4.setEnabled(false);
        }

        if (jToggleButtonI5.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(4)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI5.setEnabled(false);
        }

        if (jToggleButtonI6.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(5)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI6.setEnabled(false);
        }

        if (jToggleButtonI7.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(6)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI7.setEnabled(false);
        }

        if (jToggleButtonI8.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(7)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI8.setEnabled(false);
        }

        if (jToggleButtonI9.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(8)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI9.setEnabled(false);
        }

        if (jToggleButtonI10.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(9)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI10.setEnabled(false);
        }

        if (jToggleButtonI11.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(10)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI11.setEnabled(false);
        }

        if (jToggleButtonI12.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(11)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI12.setEnabled(false);
        }

        if (jToggleButtonI13.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(12)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI13.setEnabled(false);
        }

        if (jToggleButtonI14.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(13)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI14.setEnabled(false);
        }

        if (jToggleButtonI15.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(14)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI15.setEnabled(false);
        }

        if (jToggleButtonI16.isSelected() && secuenciaJuego.indexOf(secuenciaBotonesMostrados.charAt(15)) != -1) {
            contadorAciertos++;
        } else {
            jToggleButtonI16.setEnabled(false);
        }

        jLabelAciertos.setText(String.valueOf(contadorAciertos));

        if (contadorAciertos == numImagenesAcertar && numImagenesAcertar < 7) {
            numImagenesAcertar++;
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIconos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAciertos;
    private javax.swing.JPanel jPanelBotonIcono;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMuestra;
    private javax.swing.JToggleButton jToggleButtonI1;
    private javax.swing.JToggleButton jToggleButtonI10;
    private javax.swing.JToggleButton jToggleButtonI11;
    private javax.swing.JToggleButton jToggleButtonI12;
    private javax.swing.JToggleButton jToggleButtonI13;
    private javax.swing.JToggleButton jToggleButtonI14;
    private javax.swing.JToggleButton jToggleButtonI15;
    private javax.swing.JToggleButton jToggleButtonI16;
    private javax.swing.JToggleButton jToggleButtonI2;
    private javax.swing.JToggleButton jToggleButtonI3;
    private javax.swing.JToggleButton jToggleButtonI4;
    private javax.swing.JToggleButton jToggleButtonI5;
    private javax.swing.JToggleButton jToggleButtonI6;
    private javax.swing.JToggleButton jToggleButtonI7;
    private javax.swing.JToggleButton jToggleButtonI8;
    private javax.swing.JToggleButton jToggleButtonI9;
    // End of variables declaration//GEN-END:variables
}
